const _ = {
  AUTHFORM_FETCHING: "AUTHFORM_FETCHING",
  AUTHFORM_FETCH_ERROR: "AUTHFORM_FETCH_ERROR",
  AUTHFORM_FETCH_SUCCESS: "AUTHFORM_FETCH_SUCCESS",
  AUTHFORM_LOGOUT_SUCCESS: "AUTHFORM_FETCH_LOGOUT_SUCCESS",
  AUTHFORM_AUTHENTICATED_SUCCESS:
    "AUTHFORM_FETCH_AUTHENTICATED_SUCCESS",
};

export default _;
